### ISSUE TITLE
Gems randomly giving double XP

### ISSUE THREAD

**Issue by riffbyte** [marex-git/gemXp#20]
This bug appears randomly:
1) Take some XP from your gem.
2) Enchant something
3) Put the rest of XP in your gem.
4) You get the rest of your XP _PLUS_ the XP spent on enchant.

Sometimes it gives you more XP just when using the gem.

In my config, the empty gem is the glass bottle, and filled gem is the bottle of enchanting.

**Comment by marex-git** [comment]
Thank you for the report. For me it's not random, each enchantement does not update the experience points a player have. The effect is that you see your level going down but the plugin doesn't see it...

This seems to be bukkit fault (not mine nahjanahan lol troll) ok seriously... the getTotalExperience method in the Player class appears to have a cache functionality (guessing here, didn't look at the code), sadly when enchanting something bukkit does _not_ update this value, giving a erroneous response. That means the gems are filled with your experience _before_ the enchantment.

I will fill a bug report to bukkit (probably tonight)... If it's not fixed quickly enough I'll do a method to calculate the player experience manually or something more hacky... Sadly I don't have much free time right now, I will maybe work on this on the 25 feb...

**Comment by riffbyte** [comment]
Well, thanks for quick response!
I should disable the gems for now, will be waiting for any fix :3

**Comment by riffbyte** [comment]
Any news on the fix?

**Comment by marex-git** [comment]
No, I will make a workaround tonight...

**Comment by marex-git** [comment]
I made a workaround, here's the jar if you want to test it before the release: https://dl.dropbox.com/u/20943221/GemXp.jar

**Comment by riffbyte** [comment]
Awww, thank you :3
